#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 mrmmx31
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build GTK's lossless integer maps from the repository's Classic artwork.

Requires Pillow only at build time. Installed themes need no Python or Kvantum.
No screenshots, fonts or Irixium's separately licensed PNGs are copied.
"""
from pathlib import Path
import hashlib
import json
import sys
from PIL import Image, ImageColor

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "kvantum" / "tools"))
import button_art as button
import entry_art as entry
import menu_art as menu
import range_art as ranges
import scrollbar_art as scroll
import selection_art as selection
import tab_art as tabs

DEST = ROOT / "gtk" / "IrixClassic" / "common" / "assets"


def build_gtk2():
    header = '''# SPDX-FileCopyrightText: 2026 mrmmx31
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by gtk/tools/build_classic.py. Requires GTK2's pixmap engine.
# The theme owns drawing only; GTK owns activation, menus and selection.
gtk-enable-animations = 0
gtk-toolbar-icon-size = GTK_ICON_SIZE_SMALL_TOOLBAR
gtk-menu-images = 1
gtk-button-images = 1
gtk-color-scheme = "bg_color:#c1c1c1\\nfg_color:#000000\\nbase_color:#efefef\\ntext_color:#000000\\nselected_bg_color:#9ebfbf\\nselected_fg_color:#000000\\ntooltip_bg_color:#c1c1c1\\ntooltip_fg_color:#000000"

style "irixclassic-default" {
  xthickness = 3
  ythickness = 3
  bg[NORMAL] = "#c1c1c1"
  bg[PRELIGHT] = "#c1c1c1"
  bg[ACTIVE] = "#999999"
  bg[SELECTED] = "#9ebfbf"
  bg[INSENSITIVE] = "#c1c1c1"
  fg[NORMAL] = "#000000"
  fg[PRELIGHT] = "#000000"
  fg[ACTIVE] = "#000000"
  fg[SELECTED] = "#000000"
  fg[INSENSITIVE] = "#777777"
  base[NORMAL] = "#efefef"
  base[PRELIGHT] = "#efefef"
  base[ACTIVE] = "#b3c3c3"
  base[SELECTED] = "#9ebfbf"
  base[INSENSITIVE] = "#c1c1c1"
  text[NORMAL] = "#000000"
  text[PRELIGHT] = "#000000"
  text[ACTIVE] = "#000000"
  text[SELECTED] = "#000000"
  text[INSENSITIVE] = "#777777"
  GtkWidget::focus-line-width = 1
  GtkWidget::focus-padding = 1
  GtkWidget::focus-line-pattern = "\\1\\1"
  GtkWidget::link-color = "#0000aa"
  GtkWidget::visited-link-color = "#660066"
  GtkButton::child-displacement-x = 0
  GtkButton::child-displacement-y = 0
  GtkButton::default-border = { 1, 1, 1, 1 }
  GtkButton::image-spacing = 4
  GtkCheckButton::indicator-size = 15
  GtkCheckButton::indicator-spacing = 3
  GtkCheckMenuItem::indicator-size = 15
  GtkOptionMenu::indicator-size = { 12, 12 }
  GtkOptionMenu::indicator-spacing = { 3, 3, 1, 1 }
  GtkEntry::inner-border = { 3, 3, 1, 1 }
  GtkRange::slider-width = 18
  GtkRange::stepper-size = 18
  GtkRange::trough-border = 0
  GtkScrollbar::min-slider-length = 34
  GtkScrollbar::has-backward-stepper = 1
  GtkScrollbar::has-forward-stepper = 1
  GtkScale::slider-length = 26
  GtkScale::slider-width = 16
  GtkPaned::handle-size = 7
  GtkMenuBar::internal-padding = 0
  GtkMenu::horizontal-padding = 2
  GtkMenu::vertical-padding = 2
  GtkMenuItem::horizontal-padding = 3
  GtkTreeView::expander-size = 9
  GtkTreeView::horizontal-separator = 2
  GtkTreeView::vertical-separator = 2
  GtkToolbar::internal-padding = 1
  GtkToolbar::space-size = 7
  engine "pixmap" {
'''
    images = []

    def image(function, name, border=0, stretch=True, **attrs):
        fields = [f"function = {function}"]
        for key, value in attrs.items():
            fields.append(f'{key} = "{value}"' if key == "detail" else f"{key} = {value}")
        if stretch:
            fields += [f'file = "../common/assets/{name}.png"',
                       "border = { " + ", ".join(str(border) for _ in range(4)) + " }",
                       "stretch = TRUE"]
        else:
            # `file` + stretch FALSE tiles GTK2's drawable background. Native
            # indicators need a centered overlay, as in GTK's pixmap tutorial.
            fields += [f'overlay_file = "../common/assets/{name}.png"', "overlay_stretch = FALSE"]
        images.append("    image { " + "  ".join(fields) + " }\n")

    for gtkstate, state in (("NORMAL", "normal"), ("PRELIGHT", "normal"),
                            ("ACTIVE", "pressed"), ("SELECTED", "toggled"),
                            ("INSENSITIVE", "disabled")):
        for detail in ("button", "buttondefault", "togglebutton", "optionmenu"):
            image("BOX", f"command-{state}", 3, state=gtkstate, detail=detail)
        image("BOX", f"palettebutton-{state}", 2, state=gtkstate, detail="spinbutton_up")
        image("BOX", f"palettebutton-{state}", 2, state=gtkstate, detail="spinbutton_down")
        image("SHADOW", f"input-{'disabled' if state == 'disabled' else 'normal'}", 3, state=gtkstate, detail="entry")
        image("BOX", f"menupanel-{state}", 2, state=gtkstate, detail="menu")
        image("BOX", f"menustrip-{state}", 2, state=gtkstate, detail="menubar")
        image("BOX", f"menustrip-{state}", 2, state=gtkstate, detail="toolbar")
        image("BOX", "menurow-" + ("focused" if gtkstate in ("PRELIGHT", "SELECTED") else state), 2, state=gtkstate, detail="menuitem")
        for direction in ("up", "down", "left", "right"):
            image("ARROW", f"arrow-{direction}-{state}", stretch=False,
                  state=gtkstate, arrow_direction=direction.upper())
        image("BOX", f"palettebutton-{state}", 2, state=gtkstate, detail="stepper")
        image("BOX", f"scroll-trough-{state}", 1, state=gtkstate, detail="trough")
        for orient, suffix in (("VERTICAL", "v"), ("HORIZONTAL", "h")):
            fields = dict(state=gtkstate, orientation=orient)
            image("SLIDER", f"scroll-thumb-{suffix}-{state}", 2, detail="slider", **fields)
            # The overlay remains centered and is never resampled.
            images[-1] = images[-1].replace(" }\n", f'  overlay_file = "../common/assets/scroll-grip-{suffix}-{state}.png"  overlay_stretch = FALSE }}\n')
            image("SLIDER", f"range-thumb-{state}", 2, detail="hscale" if suffix == "h" else "vscale", **fields)
            images[-1] = images[-1].replace(" }\n", f'  overlay_file = "../common/assets/range-grip-{state}.png"  overlay_stretch = FALSE }}\n')
        image("BOX", f"meter-fill-{state}", 2, state=gtkstate, detail="bar")
        image("HANDLE", f"palettebutton-{state}", 2, state=gtkstate)
        image("EXTENSION", "tab-toggled" if gtkstate == "NORMAL" else "tab-normal", 2, state=gtkstate)
        disabled = "-disabled" if gtkstate == "INSENSITIVE" else ""
        for shadow, val in (("OUT", "off"), ("IN", "on"), ("ETCHED_IN", "mixed")):
            image("CHECK", f"check-{val}{disabled}", stretch=False, state=gtkstate, shadow=shadow)
        for shadow, val in (("OUT", "off"), ("IN", "on")):
            image("OPTION", f"radio-{val}{disabled}", stretch=False, state=gtkstate, shadow=shadow)
    image("BOX_GAP", "notebook-page", 3, detail="notebook")
    image("SHADOW", "inset-normal", 3)
    image("HLINE", "separator-h")
    image("VLINE", "separator-v")
    image("FOCUS", "focus", 1)
    footer = '''  }
}
class "GtkWidget" style "irixclassic-default"

style "irixclassic-entry" = "irixclassic-default" {
  base[NORMAL] = "#b6b6aa"
}
class "GtkEntry" style "irixclassic-entry"
class "GtkSpinButton" style "irixclassic-entry"

style "irixclassic-menuitem" = "irixclassic-default" {
  xthickness = 2
  ythickness = 2
  bg[PRELIGHT] = "#dfdfdf"
  bg[ACTIVE] = "#b3b3b3"
}
class "GtkMenuItem" style "irixclassic-menuitem"
widget_class "*<GtkMenuItem>*" style "irixclassic-menuitem"

style "irixclassic-menutitle" = "irixclassic-menuitem" {
  font_name = "Italic"
}
widget_class "*<GtkMenuBar>.<GtkMenuItem>*" style "irixclassic-menutitle"

style "irixclassic-sidebar" = "irixclassic-default" {
  base[NORMAL] = "#c1c1c1"
  base[PRELIGHT] = "#c1c1c1"
}
widget "*.sidebar" style "irixclassic-sidebar"
widget "*places-treeview*" style "irixclassic-sidebar"

style "irixclassic-tooltip" = "irixclassic-default" {
  xthickness = 3
  ythickness = 3
  bg[NORMAL] = "#c1c1c1"
  fg[NORMAL] = "#000000"
}
widget "gtk-tooltip*" style "irixclassic-tooltip"
'''
    (ROOT / "gtk" / "IrixClassic" / "gtk-2.0" / "gtkrc").write_text(header + "".join(images) + footer)


def save(name, pixels):
    image = Image.new("RGBA", (len(pixels[0]), len(pixels)))
    image.putdata([(*ImageColor.getrgb(c), 255) if c else (0, 0, 0, 0)
                   for row in pixels for c in row])
    image.save(DEST / (name + ".png"), optimize=True)


def main():
    DEST.mkdir(parents=True, exist_ok=True)
    for state in button.STATES:
        for kind in ("command", "palettebutton"):
            save(f"{kind}-{state}", button.surface(kind, state)[0])
        for kind in ("input", "inset", "option", "spin"):
            save(f"{kind}-{state}", entry.surface(kind, state)[0])
        save(f"optionmark-{state}", entry.option_marker(state))
        for kind in ("menupanel", "menustrip", "menurow"):
            save(f"{kind}-{state}", menu.surface(kind, state))
        for direction in ("up", "down", "left", "right"):
            save(f"arrow-{direction}-{state}", entry.spin_marker(state, direction))
            save(f"stepper-{direction}-{state}", scroll.arrow(state, direction))
        for kind in ("range-track", "range-thumb", "meter-track", "meter-fill", "column", "hint", "section"):
            save(f"{kind}-{state}", ranges.surface(kind, state)[0])
        save(f"range-grip-{state}", ranges.grip(state))
        save(f"scroll-trough-{state}", scroll.groove(state))
        for orientation in ("v", "h"):
            thumb = scroll.thumb(state)
            grip = scroll.grip(state)
            if orientation == "h":
                thumb, grip = scroll.transpose(thumb), scroll.transpose(grip)
            save(f"scroll-thumb-{orientation}-{state}", thumb)
            save(f"scroll-grip-{orientation}-{state}", grip)
    for kind in ("check", "radio"):
        for value in (("off", "on", "mixed") if kind == "check" else ("off", "on")):
            pixels = selection.indicator(kind, value)
            save(f"{kind}-{value}", pixels)
            disabled = [[("#858585" if c in ("#cc0000", "#0000cc", "#660000", "#000066")
                          else c) for c in row] for row in pixels]
            save(f"{kind}-{value}-disabled", disabled)
    save("stipple", [["#c1c1c1", "#999999"], ["#999999", "#c1c1c1"]])
    save("separator-h", [["#919191"] * 6, ["#ececec"] * 6])
    save("separator-v", [["#919191", "#ececec"] for _ in range(6)])
    for state in tabs.STATES:
        save(f"tab-{state}", tabs.tab(state))
    save("notebook-page", tabs.page())
    focus = [[None] * 24 for _ in range(24)]
    for k in range(24):
        focus[0][k] = focus[23][k] = "#000000" if k % 2 == 0 else None
        focus[k][0] = focus[k][23] = "#000000" if k % 2 == 0 else None
    save("focus", focus)
    build_gtk2()
    package = ROOT / "gtk" / "IrixClassic"
    manifest = {"schema": 1, "algorithm": "sha256", "files": {
        str(path.relative_to(package)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(package.rglob("*")) if path.is_file() and path.name != "MANIFEST.json"
    }}
    (package / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Built {len(list(DEST.glob('*.png')))} Classic assets")


if __name__ == "__main__":
    main()
