[General]
XftAntialias=false
XftSubPixel=none
font=Nimbus Sans [urw],12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1
fixed=Nimbus Sans [urw],12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1
smallestReadableFont=Nimbus Sans [urw],10,-1,5,400,1,0,0,0,0,0,0,0,0,0,1,Italic
toolBarFont=Nimbus Sans [urw],12,-1,5,400,1,0,0,0,0,0,0,0,0,0,1,Italic
menuFont=Nimbus Sans [urw],12,-1,5,400,1,0,0,0,0,0,0,0,0,0,1,Italic

[WM]
activeFont=Nimbus Sans [urw],12,-1,5,700,1,0,0,0,0,0,0,0,0,0,1,Bold Italic
