#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 mrmmx31
# SPDX-License-Identifier: GPL-3.0-or-later
"""Bundle original DomainOS SVGs for recoloring when the KDE palette changes.

The generated JavaScript keeps the source XML intact and only replaces color
tokens. It avoids runtime local-file requests and does not recolor SGI PNGs.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
APPLET = ROOT / 'plasma/applets/org.irixclassic.domainos.panel'
IMAGES = APPLET / 'contents/images'
OUTPUT = APPLET / 'contents/ui/Artwork.js'

FUNCTIONS = r'''
// One replacement pass prevents a target color from being replaced again when
// it happens to equal another source color. No cache or per-frame work here:
// the enclosing palette binding calls this once when its colors change.
function urls(colorMap) {
    var normalized = Object.create(null)
    var requested = colorMap || {}
    for (var token in requested) {
        if (Object.prototype.hasOwnProperty.call(requested, token))
            normalized[token.toLowerCase()] = String(requested[token])
    }
    var result = {}
    for (var filename in templates) {
        var xml = templates[filename].replace(
            /#(?:[0-9a-f]{8}|[0-9a-f]{6}|[0-9a-f]{4}|[0-9a-f]{3})\b/gi,
            function(token) {
                var replacement = normalized[token.toLowerCase()]
                // Keep source bytes, including letter case, for unchanged roles.
                if (replacement === undefined ||
                        replacement.toLowerCase() === token.toLowerCase())
                    return token
                return replacement
            })
        result[filename] = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(xml)
    }
    return result
}
'''


def generated_source():
    templates = {path.name: path.read_text(encoding='utf-8')
                 for path in sorted(IMAGES.glob('*.svg'))}
    if not templates:
        raise RuntimeError('No DomainOS SVG artwork found')
    return ('.pragma library\n'
            '// SPDX-FileCopyrightText: 2026 mrmmx31\n'
            '// SPDX-License-Identifier: GPL-3.0-or-later\n'
            '// Generated by plasma/tools/gerar-domainos-paleta.py.\n'
            '// Original SVG geometry and attribution remain in contents/images.\n'
            'var templates = ' + json.dumps(templates, ensure_ascii=False,
                                           indent=2) + '\n' + FUNCTIONS)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='verify the bundle without writing any files')
    args = parser.parse_args()
    expected = generated_source()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != expected:
            print('Artwork.js is outdated; run plasma/tools/gerar-domainos-paleta.py',
                  file=sys.stderr)
            return 1
        print('Artwork.js matches the original DomainOS SVGs')
        return 0
    OUTPUT.write_text(expected, encoding='utf-8')
    print('Generated ' + str(OUTPUT.relative_to(ROOT)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
