#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Optional legacy native Gtk2 controls; inherits private gtkrc/XSettings."""
import argparse
import json
import os
from demo_env import require_private_session
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument("--verificar",action="store_true")
args=parser.parse_args()
if args.verificar:
    import ctypes as C
    import gi
    assert "2.0" in gi.Repository.get_default().enumerate_versions("Gtk")
    library=C.CDLL("libgtk-x11-2.0.so.0")
    version=[C.c_uint.in_dll(library,"gtk_"+kind+"_version").value for kind in ("major","minor","micro")]
    print(json.dumps({"status":"ready","toolkit":"GTK2","version":".".join(map(str,version)),"gui_started":False,"gtk_initialized":False,"switch_supported":False}))
    raise SystemExit(0)
require_private_session()
import gi
gi.require_version("Gtk","2.0")
from gi.repository import Gtk
Gtk.init([])
settings=Gtk.Settings.get_default()
window=Gtk.Window()
window.set_title("NATIVEAPP GTK2 — integrated theme demo PID %d" % os.getpid())
window.set_default_size(800,510)
window.connect("destroy",Gtk.main_quit)
outer=Gtk.VBox(spacing=8)
outer.set_border_width(8)
window.add(outer)
status=Gtk.Label(label="Only artificial native controls/data")
header=Gtk.Label(label="REAL Gtk2 widgets | theme: %s | font: %s" % (settings.get_property("gtk-theme-name"),settings.get_property("gtk-font-name")))
outer.pack_start(header,False,False,0)
menubar=Gtk.MenuBar()
menuitem=Gtk.MenuItem(label="Native Menu")
menu=Gtk.Menu()
action=Gtk.MenuItem(label="Record native menu activation")
action.connect("activate",lambda _item:status.set_text("Native Gtk2 MenuItem activate signal received"))
menu.append(action)
check=Gtk.CheckMenuItem(label="Checkable menu item")
check.set_active(True)
menu.append(check)
menu.append(Gtk.SeparatorMenuItem())
disabled=Gtk.MenuItem(label="Unavailable action")
disabled.set_sensitive(False)
menu.append(disabled)
close=Gtk.MenuItem(label="Close only this demo")
close.connect("activate",lambda _item:window.destroy())
menu.append(close)
menuitem.set_submenu(menu)
menubar.append(menuitem)
outer.pack_start(menubar,False,False,0)
buttons=Gtk.HBox(spacing=8)
command=Gtk.Button(label="Press and release")
command.connect("clicked",lambda _button:status.set_text("Native Gtk2 clicked signal received"))
toggle=Gtk.ToggleButton(label="Latched toggle")
toggle.set_active(True)
unavailable=Gtk.Button(label="Disabled button")
unavailable.set_sensitive(False)
for button in (command,toggle,unavailable):buttons.pack_start(button,False,False,0)
outer.pack_start(buttons,False,False,0)
fields=Gtk.HBox(spacing=8)
for caption,editable,enabled in (("Editable native Gtk.Entry",True,True),("Read only",False,True),("Disabled field",True,False)):
    entry=Gtk.Entry()
    entry.set_text(caption)
    entry.set_editable(editable)
    entry.set_sensitive(enabled)
    fields.pack_start(entry,True,True,0)
outer.pack_start(fields,False,False,0)
checks=Gtk.HBox(spacing=8)
for caption,active,mixed,enabled in (("Off",False,False,True),("Checked",True,False,True),("Mixed",True,True,True),("Disabled",True,False,False)):
    check=Gtk.CheckButton(label=caption)
    check.set_active(active)
    check.set_inconsistent(mixed)
    check.set_sensitive(enabled)
    checks.pack_start(check,False,False,0)
outer.pack_start(checks,False,False,0)
outer.pack_start(Gtk.Label(label="Gtk2 has no GtkSwitch; no substitute is drawn"),False,False,0)
spin=Gtk.SpinButton.new_with_range(0,100,1)
spin.set_value(42)
outer.pack_start(spin,False,False,0)
scroll=Gtk.ScrolledWindow()
scroll.set_policy(Gtk.PolicyType.ALWAYS,Gtk.PolicyType.ALWAYS)
text=Gtk.TextView()
text.get_buffer().set_text("Native Gtk2 TextView\n"+("Long test text for both native scrollbars — "*5+"\n")*45)
scroll.add(text)
outer.pack_start(scroll,True,True,0)
outer.pack_start(status,False,False,0)
window.show_all()
print(json.dumps({"status":"opened","toolkit":"GTK2","pid":os.getpid(),"theme":settings.get_property("gtk-theme-name"),"font":settings.get_property("gtk-font-name"),"custom_css":False}),flush=True)
Gtk.main()
