#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""User-local theme trees: staged replacement, backups and guarded rollback."""
from contextlib import contextmanager
import fcntl
import hashlib
import json
import os
from pathlib import Path
import shutil
import uuid

from theme_transaction import Failure, atomic, no_links


def fingerprint(root):
    if not root.exists():
        return None
    no_links(root)
    if root.is_file():
        return {'@file': hashlib.sha256(root.read_bytes()).hexdigest()}
    if not root.is_dir():
        raise Failure(f'Não é um arquivo/pasta: {root}')
    result = {}
    for p in sorted(root.rglob('*')):
        rel = p.relative_to(root).as_posix()
        if rel in ('icon-theme.cache', '.icon-theme.cache'):
            continue  # generated by GTK after installation; never a source asset
        if p.is_symlink():
            result[rel] = {'link': os.readlink(p)}
        elif p.is_file():
            result[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
        elif not p.is_dir():
            raise Failure(f'Arquivo especial recusado: {p}')
    return result


def validate_source(root):
    if root.is_file():
        return
    if not root.is_dir():
        raise Failure(f'Dependência ausente: {root}')
    for p in root.rglob('*'):
        if p.is_symlink():
            resolved = p.resolve(strict=True)
            if not resolved.is_relative_to(root.resolve()) or not resolved.is_file():
                raise Failure(f'Link externo ou de pasta recusado: {p}')
        elif not (p.is_file() or p.is_dir()):
            raise Failure(f'Arquivo especial recusado: {p}')


def copy_path(source, dest, symlinks=False):
    if source.is_dir():
        shutil.copytree(source, dest, symlinks=symlinks)
    else:
        shutil.copy2(source, dest)


def remove_path(path):
    if path.is_dir():
        shutil.rmtree(path)
    else:
        path.unlink()


class Bundle:
    def __init__(self, state, destinations):
        self.state = state
        self.destinations = set(destinations)

    @contextmanager
    def locked(self):
        no_links(self.state)
        self.state.mkdir(parents=True, exist_ok=True, mode=0o700)
        path = self.state/'lock'
        no_links(path)
        with path.open('a') as stream:
            fcntl.flock(stream, fcntl.LOCK_EX | fcntl.LOCK_NB)
            yield

    def save(self, path, record):
        atomic(path, (json.dumps(record, indent=2) + '\n').encode())

    def latest(self):
        pointer = self.state/'latest'
        no_links(pointer)
        if not pointer.exists():
            return None
        token = pointer.read_text().strip()
        if len(token) != 32 or any(c not in '0123456789abcdef' for c in token):
            raise Failure('Referência de backup inválida.')
        path = self.state/'backups'/token/'receipt.json'
        no_links(path)
        record = json.loads(path.read_text())
        for entry in record['entries']:
            dest = Path(entry['destination'])
            if dest not in self.destinations:
                raise Failure(f'Destino fora do pacote: {dest}')
            no_links(dest)
        return path, record

    def install(self, sources, dry=False):
        # Validate every source and destination before staging or changing anything.
        for source, dest in sources:
            validate_source(source)
            no_links(dest)
            fingerprint(dest)
        previous = self.latest()
        if previous and previous[1]['status'] == 'prepared':
            raise Failure('Instalação interrompida; execute --restaurar antes de repetir.')
        print(f'{len(sources)} componentes locais verificados:')
        for _, dest in sources:
            print(' ', dest)
        if dry:
            return
        token = uuid.uuid4().hex
        backup = self.state/'backups'/token
        backup.mkdir(parents=True, mode=0o700)
        entries = []
        stages = []
        parked = []
        try:
            for index, (source, dest) in enumerate(sources):
                dest.parent.mkdir(parents=True, exist_ok=True)
                stage = dest.with_name('.'+dest.name+'.stage-'+token)
                stages.append(stage)
                # Internal source links become ordinary files; no external dependency.
                copy_path(source, stage)
                before = fingerprint(dest)
                after = fingerprint(stage)
                if before == after:
                    remove_path(stage)
                    continue
                saved = backup/str(index)
                if before is not None:
                    copy_path(dest, saved, symlinks=True)
                    if fingerprint(saved) != before or fingerprint(dest) != before:
                        raise Failure(f'Destino mudou durante backup: {dest}')
                entries.append({'destination': str(dest), 'saved': str(index),
                                'before': before, 'after': after, 'stage': str(stage)})
            if not entries:
                shutil.rmtree(backup)
                print('Todos os componentes já estão atualizados.')
                return
            record = {'status': 'prepared', 'entries': entries}
            receipt = backup/'receipt.json'
            self.save(receipt, record)
            atomic(self.state/'latest', (token+'\n').encode())
            try:
                for entry in entries:
                    dest = Path(entry['destination'])
                    if fingerprint(dest) != entry['before']:
                        raise Failure(f'Destino mudou durante instalação: {dest}')
                    # Rename on the same filesystem; never expose a half-copied tree.
                    if dest.exists():
                        old = dest.with_name('.'+dest.name+'.old-'+token)
                        os.replace(dest, old)
                        parked.append(old)
                    os.replace(entry['stage'], dest)
                    if fingerprint(dest) != entry['after']:
                        raise Failure(f'Conferência falhou: {dest}')
                record['status'] = 'installed'
                self.save(receipt, record)
            except BaseException:
                self.restore()
                raise
            print(f'Backup: {backup}')
        finally:
            for stage in stages + parked:
                if stage.exists():
                    remove_path(stage)

    def restore(self, dry=False):
        latest = self.latest()
        if not latest:
            raise Failure('Nenhum backup disponível.')
        receipt, record = latest
        if record['status'] not in ('prepared', 'installed'):
            raise Failure('O último backup já foi restaurado.')
        for entry in record['entries']:
            saved = entry['saved']
            if not saved.isdigit():
                raise Failure('Caminho de backup inválido.')
            if fingerprint(receipt.parent/saved) != entry['before']:
                raise Failure('Backup alterado.')
            current = fingerprint(Path(entry['destination']))
            accepted = [entry['before'], entry['after']]
            if record['status'] == 'prepared':
                accepted.append(None)
            if current not in accepted:
                raise Failure(f'Edição posterior detectada: {entry["destination"]}')
        if dry:
            print(f'Restauração verificada: {receipt.parent}')
            return
        # Mark recoverable before the first removal, including normal rollback.
        record['status'] = 'prepared'
        self.save(receipt, record)
        for entry in reversed(record['entries']):
            dest = Path(entry['destination'])
            if fingerprint(dest) == entry['before']:
                continue
            staged = dest.with_name('.'+dest.name+'.restore-'+uuid.uuid4().hex)
            try:
                if entry['before'] is not None:
                    copy_path(receipt.parent/entry['saved'], staged, symlinks=True)
                    if fingerprint(staged) != entry['before']:
                        raise Failure(f'Falha ao preparar restauração: {dest}')
                if dest.exists():
                    remove_path(dest)
                if staged.exists():
                    os.replace(staged, dest)
            finally:
                if staged.exists():
                    remove_path(staged)
        record['status'] = 'restored'
        self.save(receipt, record)
        print('Componentes anteriores restaurados; preferências preservadas.')
