#!/usr/bin/env python3
"""Generate fixed SVG tiles from the reviewed pixel matrix; no raster repaint on resize."""
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
text = (ROOT/'package/contents/ui/Pixels.js').read_text()
tiles = json.loads(re.search(r'var tiles = (\{.*?\});', text, re.S)[1])
output = ROOT/'package/contents/tiles'
output.mkdir(exist_ok=True)
for state, palette in {'active': ['#a59f80','#000000','#dad7ca','#5b5746'],
                       'inactive': ['#808080','#000000','#c6c6c6','#424242']}.items():
    for name, rows in tiles.items():
        rectangles = []
        for y, row in enumerate(rows):
            for run in re.finditer(r'(.)\1*', row):
                if run[0][0] != '.':
                    rectangles.append(f'<rect x="{run.start()}" y="{y}" width="{len(run[0])}" height="1" fill="{palette[int(run[0][0])]}"/>')
        width, height = len(rows[0]), len(rows)
        (output/f'{state}-{name}.svg').write_text(
            '<!-- SPDX-License-Identifier: GPL-3.0-or-later; generated by tools/build_tiles.py -->\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">'
            + ''.join(rectangles) + '</svg>\n')
